name: CI Test suite

on: 
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [dusk-tests]

jobs:
  dusk-php:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: nova-flexible-content-tests
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_ROOT_PASSWORD: test_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/checkout@v2
        with:
          repository: whitecube/nova-flexible-content
          path: './nova-flexible-content'
          ref: 'nova-4'

      - name: Debug
        run: pwd && ls -la
        
      - name: Prepare The Environment
        run: |
          cp .env.ci .env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          
      - name: Authenticate Nova
        run: composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_LICENSE_KEY }}

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Publish Nova Assets
        run: php artisan nova:install

      - name: Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver --detect

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &

      - name: Run Laravel Server
        run: php artisan serve > /dev/null 2>&1 &

      - name: Run Dusk Tests
        run: |
          chmod -R 0755 vendor/laravel/dusk/bin/
          php artisan pest:dusk
          
      - name: Make log file downloadable
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
